config/routes.rb
Rails.application.routes.draw do
  resources :drivers
  resources :counterparties
  resources :fuels, only: [:index, :new, :create]
  resources :salaries
  resources :truck_repairs, only: [:index, :new, :create]
  resources :trailer_repairs, only: [:index, :new, :create]
  devise_for :users
  resources :trucks
  resources :trailers
  resources :reis_tables
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  get '/profile', to: 'profiles#show', as: 'profile'
  resources :users, only: [:index] do
    patch :update_role, on: :member
  end
  
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/counterparty.rb
class Counterparty < ApplicationRecord
    enum status: { active: 'Активен', inactive: 'Неактивен' }
    has_many :reis_tables
    validates :name, :contact, :INN, :email,:post,:status, presence: true
end

app/controllers/counterparties_controller.rb
class CounterpartiesController < ApplicationController
  before_action :set_counterparty, only: [:edit, :update, :destroy]
  before_action :check_admin_or_employee, only: [:new, :create, :edit, :update, :destroy]
  def index
    @counterparties = Counterparty.all
  end

  def new
    @counterparty = Counterparty.new
  end

  def create
    @counterparty = Counterparty.new(counterparty_params)
    @counterparty.status = 'active'
    if @counterparty.save
      redirect_to counterparties_path, notice: 'Контрагент успешно создан.'
    else
      render :new
    end
  end
  def show
    @counterparty = Counterparty.find(params[:id])
  end
  def edit
  end

  def update
    if @counterparty.update(counterparty_params)
      redirect_to counterparties_path, notice: 'Информация о водителе обновлена.'
    else
      render :edit
    end
  end

  def destroy
    @counterparty.destroy
    redirect_to counterparties_path, notice: 'Контрагент удален.'
  end

  private

  def set_counterparty
    @counterparty = Counterparty.find(params[:id])
  end

  def counterparty_params
    params.require(:counterparty).permit(:name, :contact, :INN, :email, :post, :status)
  end

  def check_admin_or_employee
    redirect_to(root_path) unless current_user.admin? || current_user.employee?
  end

end

app/helpers/counterparties_helper.rb
module CounterpartiesHelper
end

app/views/counterparties/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Counterparties#create</h1>
  <p>Find me in app/views/counterparties/create.html.erb</p>
</div>

app/views/counterparties/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Counterparties#destroy</h1>
  <p>Find me in app/views/counterparties/destroy.html.erb</p>
</div>

app/views/counterparties/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">Counterparties#edit</h1>
  <p>Find me in app/views/counterparties/edit.html.erb</p>
</div>

app/views/counterparties/index.html.erb
<div class="flex justify-center bg-white shadow-lg rounded-lg w-full">
  
  <div class="p-6">
    <div class="flex justify-center items-center">
    <h1 class="text-3xl font-bold text-center my-6 col-span-5 mr-4">Список контрагентов</h1>
    <%= link_to new_counterparty_path, class: 'flex items-center justify-center h-12 w-12 bg-green-500 hover:bg-green-700 text-white rounded-full shadow-lg' do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/>
      </svg>
    <% end %>
    </div>
    <div class="gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 grid grid-cols-1">
    <% @counterparties.each do |counterparty| %>
    <%= link_to counterparty_path(counterparty)  do %>
      <div class="flex p-4 rounded-lg mb-2  shadow-md hover:bg-green-200">
        <div class="w-full flex flex-col">
        <div class="font-bold">Название: <%= counterparty.name %></div>
        <div>Контактный номер: <%= counterparty.contact %></div>
        <div>ИНН: <%= counterparty.INN %></div>
        <div>Email: <%= counterparty.email %></div>
        <div>Почтовый адрес: <%= counterparty.post %></div>
        <div>Статус: <%= counterparty.status %></div>
        </div>
      </div>
    <% end %>  
    <% end %>
    </div>
  </div>
</div>

app/views/counterparties/new.html.erb
<%= render 'form', counterparty: @counterparty %>

app/views/counterparties/show.html.erb
<%= render 'form', counterparty: @counterparty %>

app/views/counterparties/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Counterparties#update</h1>
  <p>Find me in app/views/counterparties/update.html.erb</p>
</div>