config/routes.rb
Rails.application.routes.draw do
  resources :drivers
  resources :counterparties
  resources :fuels, only: [:index, :new, :create]
  resources :salaries
  resources :truck_repairs, only: [:index, :new, :create]
  resources :trailer_repairs, only: [:index, :new, :create]
  devise_for :users
  resources :trucks
  resources :trailers
  resources :reis_tables
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  get '/profile', to: 'profiles#show', as: 'profile'
  resources :users, only: [:index] do
    patch :update_role, on: :member
  end
  
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/counterparty.rb
class Counterparty < ApplicationRecord
    enum status: { active: 'Активен', inactive: 'Неактивен' }
    has_many :reis_tables
    validates :name, :contact, :INN, :email,:post,:status, presence: true
end

app/models/driver.rb
class Driver < ApplicationRecord
    enum status: { working: 'Работает', free: 'Свободен', vacation: 'Отпуск', sick_leave: 'Больничный', fired: 'Уволен' }

    validates :lastname, :name, :patronymic, :dr_license, presence: true
    has_one_attached :photo
    has_many :salaries
    has_many :reis_tables
    def humanized_status
        case status
        when 'working'
          'Работает'
        when 'free'
          'Свободен'
        when 'vacation'
          'Отпуск'
        when 'sick_leave'
          'Больничный'
        when 'fired'
          'Уволен'
        else
          status.titleize
        end
      end
end

app/models/fuel.rb
class Fuel < ApplicationRecord
    belongs_to :truck
    validates :date, :truck_id, :fuel_l, :price, :type_f, presence: true

    enum type_f: { ai_92: 'АИ-92', ai_95: 'АИ-95', ai_98: 'АИ-98', ai_100: 'АИ-100', 
               methane: 'Метан', propane: 'Пропан', diesel: 'Дизель', 
               electricity: 'Электричество', hydrogen: 'Водород' }
end

app/models/reis_table.rb
# app/models/reis.rb
class ReisTable < ApplicationRecord
    belongs_to :counterparty
    belongs_to :driver
    belongs_to :truck
    belongs_to :trailer
  
    # Добавьте необходимые валидации и методы, например, для вычисления суммы или статуса
  end
  

app/models/salary.rb
class Salary < ApplicationRecord
    belongs_to :driver
    
end

app/models/trailer.rb
class Trailer < ApplicationRecord
    enum status: { decommissioned: 'Списан', operating: 'Работает', in_repair: 'На ремонте', idle: 'Простаивает' }
    validates :car_number, :model, :year, :VIN, :STS, :status, presence: true
    has_many :truck_repairs
    has_many :reis_tables
    has_one_attached :photo
    def humanized_status
        case status
        when 'decommissioned'
          'Списан'
        when 'operating'
          'Работает'
        when 'vacation'
          'Отпуск'
        when 'in_repair'
          'На ремонте'
        when 'idle'
          'Простаивает'
        else
          status.titleize
        end
      end
end

app/models/trailer_repair.rb
class TrailerRepair < ApplicationRecord
    belongs_to :trailer
    validates :date_repair, :part_name, :price, presence: true
end

app/models/truck.rb
class Truck < ApplicationRecord
    enum status: { decommissioned: 'Списан', operating: 'Работает', in_repair: 'На ремонте', idle: 'Простаивает' }
  
    validates :car_number, :model, :year, :VIN, :STS, :status, presence: true
    has_many :truck_repairs
    has_many :fuels
    has_many :reis_tables
    has_one_attached :photo
    def humanized_status
        case status
        when 'decommissioned'
          'Списан'
        when 'operating'
          'Работает'
        when 'vacation'
          'Отпуск'
        when 'in_repair'
          'На ремонте'
        when 'idle'
          'Простаивает'
        else
          status.titleize
        end
      end
end
  

app/models/truck_repair.rb
class TruckRepair < ApplicationRecord
    belongs_to :truck
    validates :date_repair, :part_name, :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  enum role: { admin: "admin", employee: "employee", user: "user" }
  
  before_create :set_default_role

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def admin?
    role == 'admin'
  end
  private

  def set_default_role
    self.role ||= 'user'
  end       
end

app/controllers/fuels_controller.rb
class FuelsController < ApplicationController
  def index
    @fuels = Fuel.includes(:truck).order(date: :desc)

  end

  def new
    @truck = Truck.find(params[:truck_id])
    @fuel = Fuel.new(truck_id: @truck.id)
  end
  
  def create
    @fuel = Fuel.new(fuel_params)
    if @fuel.save
      redirect_to fuels_path, notice: 'Заправка успешно добавлена.'
    else
      render :new
    end
  end
  
  private
  
  def fuel_params
    params.require(:fuel).permit(:truck_id, :date, :type_f, :fuel_l, :price)
  end

  
end

app/controllers/reis_tables_controller.rb
class ReisTablesController < ApplicationController
    def index
      #@truck_repairs = TruckRepair.all
      @reis_tables = ReisTable.all
    end
  
    def new
      @reis_table = ReisTable.new
    end
    def show
        @reis_table = ReisTable.find(params[:id])
      end
    def create
      @reis_table = ReisTable.new(reis_table_params)
      if @reis_table.save
        redirect_to reis_tables_path, notice: 'Рейс успешно добавлен.'
      else
        render :new
      end
    end
    def update
        @reis_table = ReisTable.find(params[:id])
        if @reis_table.update(reis_table_params)
          redirect_to reis_tables_path, notice: 'Информация о рейсе обновлена.'
        else
          render :reis_tables_path
        end
      end

    private

    

    def reis_table_params
      params.require(:reis_table).permit(:truck_id, :driver_id, :trailer_id, :counterparty_id,:loading,:unloading,:date_load,:date_unload,:cargo_name,:km,:rate,:tonnage,:nds,:sum,:due_date,:invoice_date,:letter_date,:deadline,:status,:tracking_number)
    end
    def check_admin_or_employee
        # Проверка, что текущий пользователь является администратором или сотрудником
        redirect_to(root_path) unless current_user.admin? || current_user.employee?
      end
  end
  

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  def index
    @trucks = Truck.all
  end

  def show
    @truck = Truck.find(params[:id])
  end
  def new
    @truck = Truck.new
  end
  def edit
    @truck = Truck.find(params[:id])
  end
  def create
    @truck = Truck.new(truck_params)
    if @truck.save
      redirect_to trucks_path, notice: 'Грузовик успешно создан.'
    else
      render :new
    end
  end
  def update
    @truck = Truck.find(params[:id])
  if @truck.update(truck_params)
    redirect_to @truck
  else
    render :edit
  end
  end

  private

  def truck_params
    params.require(:truck).permit(:car_number, :model, :year, :VIN, :STS, :status, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:update_role]
  
    def index
      @users = User.all.order(id: :asc)
    end
  
    def update_role
        if @user.update(user_params)
          redirect_to users_path, notice: "Роль обновлена"
        else
          redirect_to users_path, alert: @user.errors.full_messages.to_sentence
        end
      end
      
  
    private
  
    def set_user
      @user = User.find(params[:id])
    end
  
    def user_params
      params.require(:user).permit(:role)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/fuels_helper.rb
module FuelsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/truck_repairs_helper.rb
module TruckRepairsHelper
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/views/reis_tables/_form.html.erb
<div class="flex items-center justify-center w-full min-h-screen">
  <div class="flex -mx-2 shadow-lg">
  <div class="w-full max-w-md bg-white rounded-r px-12 pt-6 pb-8">
  <% if @reis_table.new_record? %>
      <h2 class="text-2xl font-bold text-left text-gray-700 mb-4">Новый рейс</h2>  
  <% else %>
      <h2 class="text-2xl font-bold text-left text-gray-700 mb-4">Информация о рейсе </h2>
  <% end %>
<%= form_with(model: reis_table, local: true, class: "grid grid-cols-2 gap-4") do |form| %>
    <% if reis_table.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(reis_table.errors.count, "error") %> запрещено эту форму сохранить:</h2>
  
        <ul>
          <% reis_table.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= form.label :lastname,"Контрагент", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.collection_select :counterparty_id, Counterparty.all, :id, :name, { prompt: true }, { class: 'w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500' } %>
    </div>
    <div class="field">
      <%= form.label :lastname,"Водитель", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.collection_select :driver_id, Driver.all, :id, :lastname, { prompt: true }, { class: 'w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500' } %>
    </div>
    <div class="field">
      <%= form.label :lastname,"Грузовик", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.collection_select :truck_id, Truck.all, :id, :car_number, { prompt: true }, { class: 'w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500' } %>
    </div>
    <div class="field">
      <%= form.label :lastname,"Прицеп", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.collection_select :trailer_id, Trailer.all, :id, :car_number, { prompt: true }, { class: 'w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500' } %>
    </div>
    <div class="field">
    <%= form.label :loading,"Место загрузки", class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.text_field :loading, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"   %>
    </div>
    <div class="field">
    <%= form.label :unloading,"Место разгрузки", class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.text_field :unloading, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"   %>
    </div>
    <div class="field">
    <%= form.label :date_load,"Дата загрузки", class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.date_field :date_load, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"  %>
    </div>
    <div class="field">
    <%= form.label :date_unload,"Дата разгрузки", class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.date_field :date_unload, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"  %>
    </div>
    <div class="field">
    <%= form.label :cargo_name,"Наименование груза", class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.text_field :cargo_name, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"   %>
    </div>
    <div class="field">
    <%= form.label :km,"Километраж", class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.text_field :km, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"   %>
    </div>
    <div class="field">
    <%= form.label :rate,"Ставка за тонну груза", class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.text_field :rate, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"   %>
    </div>
    <div class="field">
    <%= form.label :tonnage,"Загруженный вес", class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.text_field :tonnage, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"   %>
    </div>
    
    <div class="field">
    <%= form.label :nds,"НДС", class: "text-gray-700 text-sm font-bold mb-2  mr-2"  %>
    <%= form.check_box :nds, class: "shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"   %>
    </div>
    <div class="field">
    <%= form.label :sum,"Суммарная стоимость", class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.text_field :sum, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"   %>
    </div>
    <div class="field">
    <%= form.label :due_date,"Срок оплаты", class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.date_field :due_date, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"  %>
    </div>
    <div class="field">
    <%= form.label :invoice_date,"Дата выставления счёта", class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.date_field :invoice_date, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"  %>
    </div>
    <div class="field">
    <%= form.label :letter_date,"Дата отправки письма", class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.date_field :letter_date, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"  %>
    </div>
    <div class="field">
    <%= form.label :deadline,"Крайний срок оплаты", class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.date_field :deadline, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"  %>
    </div>
    <div class="field">
    <%= form.label :status,"Статус оплаты", class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.text_field :status, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"  %>
    </div>
    <div class="field">
    <%= form.label :tracking_number,"Номер отслеживания", class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.text_field :tracking_number, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"  %>
    </div>
    <div class="actions" >
      <% if @reis_table.new_record? %>
        <%= form.submit "Создать", class: "w-full bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500" %>
      <% else %>
        <%= form.submit "Обновить информацию", class: "w-full bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500" %>
      <% end %>
    </div>
  <% end %>
    </div>
    
  </div>
</div>

app/views/reis_tables/index.html.erb
<div class="flex justify-center bg-white shadow-lg rounded-lg w-full">
  <div class="p-6">
    <div class="flex justify-center items-center">
    <h1 class="text-3xl font-bold text-center my-6 col-span-5 mr-4">Список Рейсов</h1>
    <%= link_to new_reis_table_path, class: 'flex items-center justify-center h-12 w-12 bg-green-500 hover:bg-green-700 text-white rounded-full shadow-lg' do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/>
      </svg>
    <% end %>
    </div>
    <div class="gap-4 sm:grid-cols-3 md:grid-cols-4 grid grid-cols-1">
    <% @reis_tables.each_with_index do |reis, index| %>
    <%= link_to reis_table_path(reis)  do %>
      <div class="<%= index.even? ? 'bg-white' : 'bg-green-100' %> hover:bg-green-200 p-4 rounded-lg mb-2 shadow-md">
        <div class="text-lg font-semibold mb-2">Контрагент: <%= reis.counterparty.name %></div>
        <div class="text-lg font-semibold mb-2">Водитель: <%= reis.driver.lastname %> <%= reis.driver.name %></div>
        <div class="text-lg font-semibold mb-2">Грузовик: <%= reis.truck.car_number %></div>
        <div class="text-lg font-semibold mb-2">Прицеп: <%= reis.trailer.car_number %></div>
        <div>Место загрузки: <%= reis.loading %></div>
        <div>Место разгрузки: <%= reis.unloading %></div>
        <div>Дата загрузки: <%= reis.date_load %></div>
        <div>Дата разгрузки: <%= reis.date_unload %></div>
        <div>Наименование груза: <%= reis.cargo_name %></div>
        <div>Километраж: <%= reis.km %></div>
        <div>Ставка за тонну груза: <%= reis.rate %></div>
        <div>Количество груза: <%= reis.tonnage %></div>
        <div>Наличие налога: <%= reis.nds %></div>
        <div>Стоимость рейса: <%= reis.sum %></div>
        <div>Срок оплаты: <%= reis.due_date %></div>
        <div>Дата выставления счета: <%= reis.invoice_date %></div>
        <div>Дата отправки письма: <%= reis.letter_date %></div>
        <div>Крайний срок оплаты: <%= reis.deadline %></div>
        <div>Статус: <%= reis.status %></div>
        <div>Номер отслеживания: <%= reis.tracking_number %></div>
      </div>
      <%end%>
    <% end %>
    </div>
  </div>
</div>

app/views/reis_tables/new.html.erb
<%= render 'form', reis_table: @reis_table %>

app/views/reis_tables/show.html.erb
<%= render 'form', reis_table: @reis_table %>