config/routes.rb
Rails.application.routes.draw do
  resources :drivers
  resources :counterparties
  resources :fuels, only: [:index, :new, :create]
  resources :salaries
  resources :truck_repairs, only: [:index, :new, :create]
  resources :trailer_repairs, only: [:index, :new, :create]
  devise_for :users
  resources :trucks
  resources :trailers
  resources :reis_tables
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  get '/profile', to: 'profiles#show', as: 'profile'
  resources :users, only: [:index] do
    patch :update_role, on: :member
  end
  
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/counterparty.rb
class Counterparty < ApplicationRecord
    enum status: { active: 'Активен', inactive: 'Неактивен' }
    has_many :reis_tables
    validates :name, :contact, :INN, :email,:post,:status, presence: true
end

app/models/driver.rb
class Driver < ApplicationRecord
    enum status: { working: 'Работает', free: 'Свободен', vacation: 'Отпуск', sick_leave: 'Больничный', fired: 'Уволен' }

    validates :lastname, :name, :patronymic, :dr_license, presence: true
    has_one_attached :photo
    has_many :salaries
    has_many :reis_tables
    def humanized_status
        case status
        when 'working'
          'Работает'
        when 'free'
          'Свободен'
        when 'vacation'
          'Отпуск'
        when 'sick_leave'
          'Больничный'
        when 'fired'
          'Уволен'
        else
          status.titleize
        end
      end
end

app/models/fuel.rb
class Fuel < ApplicationRecord
    belongs_to :truck
    validates :date, :truck_id, :fuel_l, :price, :type_f, presence: true

    enum type_f: { ai_92: 'АИ-92', ai_95: 'АИ-95', ai_98: 'АИ-98', ai_100: 'АИ-100', 
               methane: 'Метан', propane: 'Пропан', diesel: 'Дизель', 
               electricity: 'Электричество', hydrogen: 'Водород' }
end

app/models/reis_table.rb
# app/models/reis.rb
class ReisTable < ApplicationRecord
    belongs_to :counterparty
    belongs_to :driver
    belongs_to :truck
    belongs_to :trailer
  
    # Добавьте необходимые валидации и методы, например, для вычисления суммы или статуса
  end
  

app/models/salary.rb
class Salary < ApplicationRecord
    belongs_to :driver
    
end

app/models/trailer.rb
class Trailer < ApplicationRecord
    enum status: { decommissioned: 'Списан', operating: 'Работает', in_repair: 'На ремонте', idle: 'Простаивает' }
    validates :car_number, :model, :year, :VIN, :STS, :status, presence: true
    has_many :truck_repairs
    has_many :reis_tables
    has_one_attached :photo
    def humanized_status
        case status
        when 'decommissioned'
          'Списан'
        when 'operating'
          'Работает'
        when 'vacation'
          'Отпуск'
        when 'in_repair'
          'На ремонте'
        when 'idle'
          'Простаивает'
        else
          status.titleize
        end
      end
end

app/models/trailer_repair.rb
class TrailerRepair < ApplicationRecord
    belongs_to :trailer
    validates :date_repair, :part_name, :price, presence: true
end

app/models/truck.rb
class Truck < ApplicationRecord
    enum status: { decommissioned: 'Списан', operating: 'Работает', in_repair: 'На ремонте', idle: 'Простаивает' }
  
    validates :car_number, :model, :year, :VIN, :STS, :status, presence: true
    has_many :truck_repairs
    has_many :fuels
    has_many :reis_tables
    has_one_attached :photo
    def humanized_status
        case status
        when 'decommissioned'
          'Списан'
        when 'operating'
          'Работает'
        when 'vacation'
          'Отпуск'
        when 'in_repair'
          'На ремонте'
        when 'idle'
          'Простаивает'
        else
          status.titleize
        end
      end
end
  

app/models/truck_repair.rb
class TruckRepair < ApplicationRecord
    belongs_to :truck
    validates :date_repair, :part_name, :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  enum role: { admin: "admin", employee: "employee", user: "user" }
  
  before_create :set_default_role

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def admin?
    role == 'admin'
  end
  private

  def set_default_role
    self.role ||= 'user'
  end       
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:edit, :update]
  before_action :check_admin_or_employee, only: [:edit, :update]

  def index
    @drivers = Driver.all
  end

  def new
    @driver = Driver.new
  end
  def show
    @driver = Driver.find(params[:id])
  end
  def create
    @driver = Driver.new(driver_params)
    @driver.status = 'free'
    if @driver.save
      redirect_to drivers_path, notice: 'Водитель успешно создан.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @driver.update(driver_params)
      redirect_to drivers_path, notice: 'Информация о водителе обновлена.'
    else
      render :edit
    end
  end

  private

  def set_driver
    @driver = Driver.find(params[:id])
  end

  def driver_params
    params.require(:driver).permit(:lastname, :name, :patronymic, :dr_license, :status, :photo)
  end

  def check_admin_or_employee
    # Проверка, что текущий пользователь является администратором или сотрудником
    redirect_to(root_path) unless current_user.admin? || current_user.employee?
  end
end

app/controllers/fuels_controller.rb
class FuelsController < ApplicationController
  def index
    @fuels = Fuel.includes(:truck).order(date: :desc)

  end

  def new
    @truck = Truck.find(params[:truck_id])
    @fuel = Fuel.new(truck_id: @truck.id)
  end
  
  def create
    @fuel = Fuel.new(fuel_params)
    if @fuel.save
      redirect_to fuels_path, notice: 'Заправка успешно добавлена.'
    else
      render :new
    end
  end
  
  private
  
  def fuel_params
    params.require(:fuel).permit(:truck_id, :date, :type_f, :fuel_l, :price)
  end

  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    # Дополнительная логика, если требуется
  end
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  def index
    @trucks = Truck.all
  end

  def show
    @truck = Truck.find(params[:id])
  end
  def new
    @truck = Truck.new
  end
  def edit
    @truck = Truck.find(params[:id])
  end
  def create
    @truck = Truck.new(truck_params)
    if @truck.save
      redirect_to trucks_path, notice: 'Грузовик успешно создан.'
    else
      render :new
    end
  end
  def update
    @truck = Truck.find(params[:id])
  if @truck.update(truck_params)
    redirect_to @truck
  else
    render :edit
  end
  end

  private

  def truck_params
    params.require(:truck).permit(:car_number, :model, :year, :VIN, :STS, :status, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:update_role]
  
    def index
      @users = User.all.order(id: :asc)
    end
  
    def update_role
        if @user.update(user_params)
          redirect_to users_path, notice: "Роль обновлена"
        else
          redirect_to users_path, alert: @user.errors.full_messages.to_sentence
        end
      end
      
  
    private
  
    def set_user
      @user = User.find(params[:id])
    end
  
    def user_params
      params.require(:user).permit(:role)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counterparties_helper.rb
module CounterpartiesHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/fuels_helper.rb
module FuelsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/truck_repairs_helper.rb
module TruckRepairsHelper
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/views/drivers/_form.html.erb
<div class="flex items-center justify-center w-full min-h-screen">
  <div class="flex -mx-2 shadow-lg">
  <div class="w-full max-w-lg hidden sm:flex">
      <% if driver.photo.attached? %>
        <%= image_tag driver.photo, class: "object-cover rounded-l" %>
      <% end %>
  </div>
  <div class="w-full max-w-md bg-white rounded-r px-12 pt-6 pb-8">
  <% if @driver.new_record? %>
      <h2 class="text-2xl font-bold text-left text-gray-700 mb-4">Новый водитель</h2>  
  <% else %>
      <h2 class="text-2xl font-bold text-left text-gray-700 mb-4"><%= @driver.lastname %> <%= @driver.name %> </h2>
  <% end %>
<%= form_with(model: driver, local: true, class: "flex flex-col gap-y-4") do |form| %>
    <% if driver.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(driver.errors.count, "error") %> запрещено эту форму сохранить:</h2>
  
        <ul>
          <% driver.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <% if !@driver.new_record? %>
    <div class="flex ">
    <%= link_to new_salary_path(driver_id: @driver.id), class: 'mr-4 flex items-center justify-center hover:bg-green-700 h-12 w-12 bg-green-500 text-white rounded-full shadow-lg' do %>
     <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" fill="#FFFFFF" width="24"><path d="M444-200h70v-50q50-9 86-39t36-89q0-42-24-77t-96-61q-60-20-83-35t-23-41q0-26 18.5-41t53.5-15q32 0 50 15.5t26 38.5l64-26q-11-35-40.5-61T516-710v-50h-70v50q-50 11-78 44t-28 74q0 47 27.5 76t86.5 50q63 23 87.5 41t24.5 47q0 33-23.5 48.5T486-314q-33 0-58.5-20.5T390-396l-66 26q14 48 43.5 77.5T444-252v52Zm36 120q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Zm0-80q134 0 227-93t93-227q0-134-93-227t-227-93q-134 0-227 93t-93 227q0 134 93 227t227 93Zm0-320Z"/></svg>
    <% end %>
    </div>
    <% end %> 
    <div class="field">
      <%= form.label :lastname,"Фамилия", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_field :lastname, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500" %>
    </div>

    <div class="field">
    <%= form.label :name,"Имя", class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.text_field :name, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"  %>
    </div>
    <div class="field">
    <%= form.label :patronymic,"Отчество", class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.text_field :patronymic, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"   %>
    </div>
        <div class="field">
      <%= form.label :photo %>
      <%= form.file_field :photo %>
    </div>
    <div class="field">
    <%= form.label :dr_license,"Водительское удостоверение", class: "block text-gray-700 text-sm font-bold mb-2"   %>
    <%= form.text_field :dr_license, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"   %>
    </div>
    <% if !@driver.new_record? %>
    <div class="field">
      <%= form.label :status, "Статус", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.select :status, Driver.statuses.keys.map { |key| [Driver.statuses[key].titleize, key] }, {}, { class: "w-full shadow border rounded py-2 pr-8 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500" } %>
    </div>
    <% end %>
  
    <div class="actions" >
      <% if @driver.new_record? %>
        <%= form.submit "Создать водителя", class: "w-full bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500" %>
      <% else %>
        <%= form.submit "Обновить информацию", class: "w-full bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500" %>
      <% end %>
    </div>
  <% end %>
    </div>
    
  </div>
</div>

app/views/drivers/create.html.erb
<h1>Drivers#create</h1>
<p>Find me in app/views/drivers/create.html.erb</p>

app/views/drivers/edit.html.erb
<h1>Редактирование Водителя</h1>

<%= render 'form', driver: @driver %>

app/views/drivers/index.html.erb
<div class="flex justify-center bg-white shadow-lg rounded-lg w-full">
  
  <div class="p-6">
    <div class="flex justify-center items-center">
    <h1 class="text-3xl font-bold text-center my-6 col-span-5 mr-4">Список водителей</h1>
    <%= link_to new_driver_path, class: 'flex items-center justify-center h-12 w-12 bg-green-500 hover:bg-green-700 text-white rounded-full shadow-lg' do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/>
      </svg>
    <% end %>
    <%= link_to salaries_path, class: 'flex items-center justify-center ml-2 h-12 w-12 bg-green-500 hover:bg-green-700 text-white rounded-full shadow-lg ' do %>
      <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" fill="#FFFFFF" width="24"><path d="M444-200h70v-50q50-9 86-39t36-89q0-42-24-77t-96-61q-60-20-83-35t-23-41q0-26 18.5-41t53.5-15q32 0 50 15.5t26 38.5l64-26q-11-35-40.5-61T516-710v-50h-70v50q-50 11-78 44t-28 74q0 47 27.5 76t86.5 50q63 23 87.5 41t24.5 47q0 33-23.5 48.5T486-314q-33 0-58.5-20.5T390-396l-66 26q14 48 43.5 77.5T444-252v52Zm36 120q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Zm0-80q134 0 227-93t93-227q0-134-93-227t-227-93q-134 0-227 93t-93 227q0 134 93 227t227 93Zm0-320Z"/></svg>
    <% end %>
    </div>
    <div class="gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 grid grid-cols-1">
    <% @drivers.each do |driver| %>
    <%= link_to driver_path(driver)  do %>
      <div class="flex p-4 rounded-lg mb-2 shadow-md hover:bg-green-200">
        <% if driver.photo.attached? %>
          <%= image_tag driver.photo, class: "w-36 h-36 mt-3 object-cover mr-2"  %>
        <% end %>
        <div class="w-full flex flex-col">
        <div>Фамилия: <%= driver.lastname %></div>
        <div>Имя: <%= driver.name %></div>
        <div>Отчество: <%= driver.patronymic %></div>
        <div>Водительское удостоверение: <%= driver.dr_license %></div>
        <div>Статус: <%= driver.humanized_status %></div>
        </div>
      </div>
    <% end %>  
    <% end %>
    </div>
  </div>
</div>

app/views/drivers/new.html.erb
<%= render 'form', driver: @driver %>

app/views/drivers/show.html.erb
<%= render 'form', driver: @driver %>

app/views/drivers/update.html.erb
<h1>Редактирование Водителя</h1>

<%= render 'form', driver: @driver %>

app/views/fuels/create.html.erb
<h1>Fuels#create</h1>
<p>Find me in app/views/fuels/create.html.erb</p>

app/views/fuels/new.html.erb
<%= render 'form', fuel: @fuel %>

app/views/trucks/_form.html.erb
<div class="flex items-center justify-center w-full min-h-screen">
  <div class="flex -mx-2 shadow-lg">
  <div class="w-full max-w-lg hidden sm:flex">
      <% if truck.photo.attached? %>
        <%= image_tag truck.photo, class: "object-cover rounded-l" %>
      <% end %>
  </div>
  <div class="w-full max-w-md bg-white rounded-r px-12 pt-6 pb-8">
  <% if @truck.new_record? %>
      <h2 class="text-2xl font-bold text-left text-gray-700 mb-4">Новый грузовик</h2>  
  <% else %>
      <h2 class="text-2xl font-bold text-left text-gray-700 mb-4"><%= @truck.model %> <%= @truck.car_number %> </h2>
  <% end %>
<%= form_with(model: truck, local: true, class: "flex flex-col gap-y-4") do |form| %>
    <% if truck.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(truck.errors.count, "error") %> запрещено эту форму сохранить:</h2>
  
        <ul>
          <% truck.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <% if !@truck.new_record? %>
    <div class="flex ">
    <%= link_to new_truck_repair_path(truck_id: @truck.id), class: 'mr-4 flex items-center justify-center hover:bg-green-700 h-12 w-12 bg-green-500 text-white rounded-full shadow-lg' do %>
      <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path fill="#FFFFFF" d="M756-120 537-339l84-84 219 219-84 84Zm-552 0-84-84 276-276-68-68-28 28-51-51v82l-28 28-121-121 28-28h82l-50-50 142-142q20-20 43-29t47-9q24 0 47 9t43 29l-92 92 50 50-28 28 68 68 90-90q-4-11-6.5-23t-2.5-24q0-59 40.5-99.5T701-841q15 0 28.5 3t27.5 9l-99 99 72 72 99-99q7 14 9.5 27.5T841-701q0 59-40.5 99.5T701-561q-12 0-24-2t-23-7L204-120Z"/></svg>
    <% end %>

    <%= link_to new_fuel_path(truck_id: @truck.id), class: 'flex items-center justify-center hover:bg-green-700 h-12 w-12 bg-green-500 text-white rounded-full shadow-lg' do %>
      <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path fill="#FFFFFF" d="M160-120v-640q0-33 23.5-56.5T240-840h240q33 0 56.5 23.5T560-760v280h40q33 0 56.5 23.5T680-400v180q0 17 11.5 28.5T720-180q17 0 28.5-11.5T760-220v-288q-9 5-19 6.5t-21 1.5q-42 0-71-29t-29-71q0-32 17.5-57.5T684-694l-84-84 42-42 148 144q15 15 22.5 35t7.5 41v380q0 42-29 71t-71 29q-42 0-71-29t-29-71v-200h-60v300H160Zm80-440h240v-200H240v200Zm480 0q17 0 28.5-11.5T760-600q0-17-11.5-28.5T720-640q-17 0-28.5 11.5T680-600q0 17 11.5 28.5T720-560ZM240-200h240v-280H240v280Zm240 0H240h240Z"/></svg>
    <% end %>
    </div>
    <% end %>
    
    <div class="field">
      <%= form.label :car_number,"Номер грузовика", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_field :car_number, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500" %>
    </div>
    <div class="field">
      <%= form.label :photo %>
      <%= form.file_field :photo %>
    </div>
    <div class="field">
    <%= form.label :model,"Модель", class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.text_field :model, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"  %>
    </div>
    <div class="field">
    <%= form.label :year,"Год выпуска", class: "block text-gray-700 text-sm font-bold mb-2"  %>
    <%= form.text_field :year, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"   %>
    </div>
    <div class="field">
    <%= form.label :VIN,"VIN", class: "block text-gray-700 text-sm font-bold mb-2"   %>
    <%= form.text_field :VIN, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"   %>
    </div>
    <div class="field">
    <%= form.label :STS,"СТС", class: "block text-gray-700 text-sm font-bold mb-2"   %>
    <%= form.text_field :STS, class: "w-full shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500"   %>
    </div>
    <div class="field">
      <%= form.label :status, "Статус", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.select :status, Truck.statuses.keys.map { |key| [Truck.statuses[key].titleize, key] }, {}, { class: "w-full shadow border rounded py-2 pr-8 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500" } %>
    </div>
  
    <div class="actions" >
      <% if @truck.new_record? %>
        <%= form.submit "Создать Грузовик", class: "w-full bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500" %>
      <% else %>
        <%= form.submit "Обновить информацию", class: "w-full bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline focus:ring-green-500 focus:border-green-500" %>
      <% end %>
    </div>
  <% end %>
    </div>
    
  </div>
</div>

app/views/trucks/edit.html.erb
<h1>Редактирование Грузовика</h1>

<%= form_with(model: @truck, local: true) do |form| %>
  <% if @truck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@truck.errors.count, "error") %> запрещено эту форму сохранить:</h2>

      <ul>
      <% @truck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :car_number %>
    <%= form.text_field :car_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Назад', trucks_path %>

app/views/trucks/index.html.erb
<div class="flex justify-center bg-white shadow-lg rounded-lg w-full">
  
  <div class="p-6">
    <div class="flex justify-center items-center">
    <h1 class="text-3xl font-bold text-center my-6 col-span-5 mr-4">Список грузовиков</h1>
    <%= link_to new_truck_path, class: 'flex items-center justify-center h-12 w-12 bg-green-500 hover:bg-green-700 text-white rounded-full shadow-lg' do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/>
      </svg>
    <% end %>
    <%= link_to fuels_path, class: 'flex ml-2 items-center justify-center hover:bg-green-700 h-12 w-12 bg-green-500 text-white rounded-full shadow-lg' do %>
      <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path fill="#FFFFFF" d="M160-120v-640q0-33 23.5-56.5T240-840h240q33 0 56.5 23.5T560-760v280h40q33 0 56.5 23.5T680-400v180q0 17 11.5 28.5T720-180q17 0 28.5-11.5T760-220v-288q-9 5-19 6.5t-21 1.5q-42 0-71-29t-29-71q0-32 17.5-57.5T684-694l-84-84 42-42 148 144q15 15 22.5 35t7.5 41v380q0 42-29 71t-71 29q-42 0-71-29t-29-71v-200h-60v300H160Zm80-440h240v-200H240v200Zm480 0q17 0 28.5-11.5T760-600q0-17-11.5-28.5T720-640q-17 0-28.5 11.5T680-600q0 17 11.5 28.5T720-560ZM240-200h240v-280H240v280Zm240 0H240h240Z"/></svg>
    <% end %>
    <%= link_to truck_repairs_path, class: 'mr-4 ml-2 flex items-center justify-center hover:bg-green-700 h-12 w-12 bg-green-500 text-white rounded-full shadow-lg' do %>
      <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path fill="#FFFFFF" d="M756-120 537-339l84-84 219 219-84 84Zm-552 0-84-84 276-276-68-68-28 28-51-51v82l-28 28-121-121 28-28h82l-50-50 142-142q20-20 43-29t47-9q24 0 47 9t43 29l-92 92 50 50-28 28 68 68 90-90q-4-11-6.5-23t-2.5-24q0-59 40.5-99.5T701-841q15 0 28.5 3t27.5 9l-99 99 72 72 99-99q7 14 9.5 27.5T841-701q0 59-40.5 99.5T701-561q-12 0-24-2t-23-7L204-120Z"/></svg>
    <% end %>
    </div>
    <div class="gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 grid grid-cols-1">
    <% @trucks.each do |truck| %>
    <%= link_to truck_path(truck)  do %>
      <div class="flex p-4 rounded-lg mb-2 shadow-md hover:bg-green-200">
        <% if truck.photo.attached? %>
          <%= image_tag truck.photo, class: "w-32 h-32 object-cover mr-2"  %>
        <% end %>
        <div class="w-full flex flex-col">
        <div>Номер грузовика: <%= truck.car_number %></div>
        <div>Модель грузовика: <%= truck.model %></div>
        <div>VIN: <%= truck.VIN %></div>
        <div>СТС: <%= truck.STS %></div>
        <div>Статус: <%= truck.humanized_status %></div>
        </div>
      </div>
    <% end %>  
    <% end %>
    </div>
  </div>
</div>

app/views/trucks/new.html.erb
<%= render 'form', truck: @truck %>